### ISSUE TITLE
Choose and setup an example to work on

### ISSUE THREAD

**Issue by davenathanael** [react-boilerplate/cra-template-examples#2]
Hello,
I'm wondering if is there a preferred way to choose an example from this repo and make it dev-ready? Or rather, is the repo's purpose is only to collect examples of different usages, not to "extend" the base template and make it reusable?

Say I might want to reuse the connected-react-router example available here for multiple project, maybe I can do something like `npm run choose connected-react-router` and will clean everything else, do `npm install`, init git repository, etc.

Is it possible and fit the purpose of the repository?
Thanks!

**Comment by Can-Sahin** [comment]
Nope. These will be only examples and nothing more. Its hard to maintain one repo enough. Cannot maintain such functionality here sorry 😔
